spring:
  application:
    name: spring-ai-agents

  ai:
    openai:
      api-key: ${DASH_SCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: deepseek-v3
          temperature: 1
      embedding:
        enabled: false

    # agents
    agents:
      - name: customerServiceAgent
        instructions: |
          你是一个客户服务助理，专门负责处理客户咨询和问题。
          你需要：
          1. 耐心倾听客户问题
          2. 提供准确的信息
          3. 保持礼貌和专业
          4. 在无法解决时及时转接人工客服
        tools:
          - dateTimeTools
          # - emailTool

      - name: orderServiceAgent
        instructions: classpath:instructions/order-service.txt
        tools:
          - dateTimeTools

      - name: assistant
        instructions: You are a helpful assistant
        handoffs:
          - customerServiceAgent
          - orderServiceAgent
        tools:
          - dateTimeTools

      - name: historyTutor
        instructions: You provide assistance with historical queries. Explain important events and context clearly.
        handoffDescription: Specialist agent for historical questions

      - name: mathTutor
        instructions: You provide help with math problems. Explain your reasoning at each step and include examples
        handoffDescription: Specialist agent for math questions

      - name: triageAgent
        instructions: You determine which agent/tools to use based on the user's homework question
        handoffs:
          - historyTutor
          - mathTutor